pub const CAMERA_MOVE_SPEED: f32 = 10.0;
pub const CAMERA_PAN_SPEED: f32 = 0.05;
pub const CAMERA_ROTATION_SPEED: f32 = 0.005;
pub const CAPTURE_HEIGHT_MAP_SIZE: u32 = 256;
pub const CAPTURE_HEIGHT_MAP_DISTANCE: f32 = 100.0;
pub const CAPTURE_HEIGHT_MAP_DEPTH: f32 = 100.0;
pub const CAPTURE_HEIGHT_MAP_UPDATE_DISTANCE: f32 = 10.0;
pub const SSAO_KERNEL_SIZE: usize = 64; // must match with scene_constants.glsl
pub const SSAO_RADIUS: f32 = 2.0;
pub const LIGHT_PROBE_SIZE: u32 = 256;
pub const RENDER_OBJECT_FOR_LIGHT_PROBE: bool = false;
pub const MAX_BONES: usize = 128 * 128; // must match with scene_constants.glsl